n = input("Digite algo: ")
print('O tipo desse valor é', type(n))
print('Só tem espaços?', n.isspace())
print('É um número?', n.isnumeric())
print('É alfabético?', n.isalpha())
print('É alfanumérico?', n.isalnum())
print('Está em maiusculo?', n.isupper())
print('Está em minuscula?', n.islower())
